#!/bin/bash
# Copyright 1999-2005 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: /var/cvsroot/gentoo/src/installer/src/fe/installer-dialog,v 1.1 2005/06/12 09:48:25 robbat2 Exp $

# The next line should be set by the emerge process
export INSTALL_DIR=/opt/installer

export PYTHONPATH="${INSTALL_DIR}"
${INSTALL_DIR}/fe/dialog/dialogfe.py "$@"
